<?php
$data = array (
  0 => 
  array (
    'cat_id' => '445',
    'cat_name' => '燕之坊',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '1',
    'goods_num' => '1',
  ),
  1 => 
  array (
    'cat_id' => '162',
    'cat_name' => '日化',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '2',
    'goods_num' => '11',
  ),
  2 => 
  array (
    'cat_id' => '153',
    'cat_name' => '杯壶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '25',
    'cat_name' => '家纺/家饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 6,
  ),
  4 => 
  array (
    'cat_id' => '149',
    'cat_name' => '家电/数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 143,
  ),
  5 => 
  array (
    'cat_id' => '151',
    'cat_name' => '厨具/电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '3',
    'has_children' => '10',
    'goods_num' => 50,
  ),
  6 => 
  array (
    'cat_id' => '152',
    'cat_name' => '瓷器/杯壶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 19,
  ),
  7 => 
  array (
    'cat_id' => '154',
    'cat_name' => '保鲜/饭盒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => '4',
  ),
  8 => 
  array (
    'cat_id' => '155',
    'cat_name' => '皮具/箱包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '5',
    'goods_num' => 12,
  ),
  9 => 
  array (
    'cat_id' => '274',
    'cat_name' => '居家/服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '2',
    'goods_num' => '9',
  ),
  10 => 
  array (
    'cat_id' => '463',
    'cat_name' => '食品/粗粮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '275',
    'cat_name' => '生活/保健',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '2',
    'goods_num' => 21,
  ),
  12 => 
  array (
    'cat_id' => '159',
    'cat_name' => '工艺/日化',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '2',
    'goods_num' => '1',
  ),
  13 => 
  array (
    'cat_id' => '161',
    'cat_name' => '汽车/配件/户外',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '8',
    'goods_num' => 5,
  ),
  14 => 
  array (
    'cat_id' => '160',
    'cat_name' => '商务/办公/用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '2',
    'goods_num' => 4,
  ),
  15 => 
  array (
    'cat_id' => '475',
    'cat_name' => '花草茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  16 => 
  array (
    'cat_id' => '163',
    'cat_name' => '四件套',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => '8',
  ),
  17 => 
  array (
    'cat_id' => '164',
    'cat_name' => '三件套',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 9,
  ),
  18 => 
  array (
    'cat_id' => '165',
    'cat_name' => '被套',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '166',
    'cat_name' => '床单',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '180',
    'cat_name' => '被子系列',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => '2',
  ),
  21 => 
  array (
    'cat_id' => '179',
    'cat_name' => '绒毯系列',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '5',
    'goods_num' => '4',
  ),
  22 => 
  array (
    'cat_id' => '202',
    'cat_name' => '靠垫',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '2',
    'goods_num' => '2',
  ),
  23 => 
  array (
    'cat_id' => '205',
    'cat_name' => '枕头、枕芯',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '4',
    'goods_num' => '3',
  ),
  24 => 
  array (
    'cat_id' => '206',
    'cat_name' => '席子',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '11',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '333',
    'cat_name' => '微信产品',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '114',
    'cat_name' => '体温计',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '111',
    'cat_name' => '按摩枕',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '106',
    'cat_name' => '脂肪秤、电子秤',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '47',
  ),
  29 => 
  array (
    'cat_id' => '112',
    'cat_name' => '治疗仪',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '109',
    'cat_name' => '电动牙刷',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '126',
    'cat_name' => '足浴器',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '113',
    'cat_name' => '计步器',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '110',
    'cat_name' => '脂肪测量器',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
  ),
  34 => 
  array (
    'cat_id' => '105',
    'cat_name' => '血压计',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 6,
  ),
  35 => 
  array (
    'cat_id' => '308',
    'cat_name' => '鼠标',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '59',
    'cat_name' => '耳机',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 6,
  ),
  37 => 
  array (
    'cat_id' => '95',
    'cat_name' => '鼠标垫',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 6,
  ),
  38 => 
  array (
    'cat_id' => '140',
    'cat_name' => 'U盘',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 16,
  ),
  39 => 
  array (
    'cat_id' => '119',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 24,
  ),
  40 => 
  array (
    'cat_id' => '307',
    'cat_name' => '数码套组礼盒',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '145',
    'cat_name' => 'MP3',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
  ),
  42 => 
  array (
    'cat_id' => '66',
    'cat_name' => '音响',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 10,
  ),
  43 => 
  array (
    'cat_id' => '403',
    'cat_name' => '定做广告伞',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '404',
    'cat_name' => '定做购物袋',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '405',
    'cat_name' => '定做广告衫',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '256',
    'cat_name' => '竹筷',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  47 => 
  array (
    'cat_id' => '361',
    'cat_name' => '不锈钢',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '346',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '343',
    'cat_name' => '两件套',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  50 => 
  array (
    'cat_id' => '344',
    'cat_name' => '三件套',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  51 => 
  array (
    'cat_id' => '345',
    'cat_name' => '四件套',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '349',
    'cat_name' => '陶瓷刀',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '39',
  ),
  53 => 
  array (
    'cat_id' => '350',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '347',
    'cat_name' => '果盘',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '348',
    'cat_name' => '调味瓶',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '263',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '15',
    'goods_num' => 33,
  ),
  57 => 
  array (
    'cat_id' => '264',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '13',
    'goods_num' => 10,
  ),
  58 => 
  array (
    'cat_id' => '43',
    'cat_name' => '电子产品',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '50',
    'cat_name' => '数码配件',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => 19,
  ),
  60 => 
  array (
    'cat_id' => '52',
    'cat_name' => '时尚影音',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '6',
    'has_children' => '2',
    'goods_num' => 5,
  ),
  61 => 
  array (
    'cat_id' => '219',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 3,
  ),
  62 => 
  array (
    'cat_id' => '271',
    'cat_name' => '不锈钢类',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '272',
    'cat_name' => '铸铁类',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '273',
    'cat_name' => '提锅类',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '227',
    'cat_name' => '炊具',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 3,
  ),
  66 => 
  array (
    'cat_id' => '88',
    'cat_name' => '锅组套装',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '4',
    'goods_num' => 83,
  ),
  67 => 
  array (
    'cat_id' => '147',
    'cat_name' => '储物容器',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 19,
  ),
  68 => 
  array (
    'cat_id' => '87',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 12,
  ),
  69 => 
  array (
    'cat_id' => '448',
    'cat_name' => '砧板',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  70 => 
  array (
    'cat_id' => '99',
    'cat_name' => '刀具',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 20,
  ),
  71 => 
  array (
    'cat_id' => '296',
    'cat_name' => '调味瓶',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '26',
  ),
  72 => 
  array (
    'cat_id' => '355',
    'cat_name' => '装饰品',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '450',
    'cat_name' => '杯具',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '451',
    'cat_name' => '壶类',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '9',
  ),
  75 => 
  array (
    'cat_id' => '311',
    'cat_name' => '炊具',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 5,
  ),
  76 => 
  array (
    'cat_id' => '276',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 30,
  ),
  77 => 
  array (
    'cat_id' => '292',
    'cat_name' => '杯',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '281',
    'cat_name' => '玻璃保鲜盒系列',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => '59',
  ),
  79 => 
  array (
    'cat_id' => '283',
    'cat_name' => '瓷器保鲜盒系列',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => '3',
  ),
  80 => 
  array (
    'cat_id' => '295',
    'cat_name' => '不锈钢保鲜盒系列',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 13,
  ),
  81 => 
  array (
    'cat_id' => '239',
    'cat_name' => '锁匙包',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => '15',
  ),
  82 => 
  array (
    'cat_id' => '242',
    'cat_name' => '旅行箱包',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => '26',
  ),
  83 => 
  array (
    'cat_id' => '291',
    'cat_name' => '休闲背包',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '5',
    'goods_num' => 18,
  ),
  84 => 
  array (
    'cat_id' => '241',
    'cat_name' => '男款',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => '38',
  ),
  85 => 
  array (
    'cat_id' => '243',
    'cat_name' => '女款',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '265',
    'cat_name' => '毛巾',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '43',
  ),
  87 => 
  array (
    'cat_id' => '266',
    'cat_name' => '储物纳箱',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  88 => 
  array (
    'cat_id' => '267',
    'cat_name' => '拖把',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  89 => 
  array (
    'cat_id' => '270',
    'cat_name' => '晾衣架',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  90 => 
  array (
    'cat_id' => '321',
    'cat_name' => '雨具',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  91 => 
  array (
    'cat_id' => '310',
    'cat_name' => '指甲包套装',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '35',
  ),
  92 => 
  array (
    'cat_id' => '284',
    'cat_name' => '梳子',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  93 => 
  array (
    'cat_id' => '198',
    'cat_name' => '睡衣',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  94 => 
  array (
    'cat_id' => '199',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '200',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  96 => 
  array (
    'cat_id' => '201',
    'cat_name' => '丝巾、围巾',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 8,
  ),
  97 => 
  array (
    'cat_id' => '249',
    'cat_name' => '领带',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '324',
    'cat_name' => '手套',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '415',
    'cat_name' => '鼠标垫',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '412',
    'cat_name' => '计算器',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '409',
    'cat_name' => '公文夹',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '406',
    'cat_name' => '活页本',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '413',
    'cat_name' => 'U盘',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '443',
    'cat_name' => '邀请函',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  105 => 
  array (
    'cat_id' => '410',
    'cat_name' => '商务签字笔',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '407',
    'cat_name' => '笔记本',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '414',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '411',
    'cat_name' => '名片盒',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '408',
    'cat_name' => '拉链包',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '269',
    'cat_name' => '开业摆件',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => '6',
  ),
  111 => 
  array (
    'cat_id' => '268',
    'cat_name' => '精美饰品',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => '73',
  ),
  112 => 
  array (
    'cat_id' => '53',
    'cat_name' => '商务广告',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 10,
  ),
  113 => 
  array (
    'cat_id' => '158',
    'cat_name' => '办公用品',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '11',
    'goods_num' => 65,
  ),
  114 => 
  array (
    'cat_id' => '288',
    'cat_name' => '车载吸尘器',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => '2',
  ),
  115 => 
  array (
    'cat_id' => '302',
    'cat_name' => '车载加湿器',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => '3',
  ),
  116 => 
  array (
    'cat_id' => '277',
    'cat_name' => '冷热箱',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '10',
  ),
  117 => 
  array (
    'cat_id' => '298',
    'cat_name' => '记录仪',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '9',
  ),
  118 => 
  array (
    'cat_id' => '290',
    'cat_name' => '车饰',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 2,
  ),
  119 => 
  array (
    'cat_id' => '424',
    'cat_name' => '户外用品',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '299',
    'cat_name' => '车载工具',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '13',
  ),
  121 => 
  array (
    'cat_id' => '257',
    'cat_name' => '车载净化器',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 6,
  ),
  122 => 
  array (
    'cat_id' => '334',
    'cat_name' => '个人护理',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '449',
    'cat_name' => '毛巾',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  124 => 
  array (
    'cat_id' => '168',
    'cat_name' => '全棉四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 14,
  ),
  125 => 
  array (
    'cat_id' => '169',
    'cat_name' => '舒香棉四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '170',
    'cat_name' => '云貂绒四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '322',
    'cat_name' => '雪狐绒四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '167',
    'cat_name' => '婚庆四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '171',
    'cat_name' => '单人床全棉三件套',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '172',
    'cat_name' => '双人床全棉三件套（被套+枕套）',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  131 => 
  array (
    'cat_id' => '173',
    'cat_name' => '双人床全棉三件套（床单+枕套）',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 6,
  ),
  132 => 
  array (
    'cat_id' => '301',
    'cat_name' => '高支纯棉被套',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  133 => 
  array (
    'cat_id' => '300',
    'cat_name' => '高支纯棉床单',
    'measure_unit' => '',
    'parent_id' => '166',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  134 => 
  array (
    'cat_id' => '181',
    'cat_name' => '单层绒毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  135 => 
  array (
    'cat_id' => '182',
    'cat_name' => '双层绒毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  136 => 
  array (
    'cat_id' => '186',
    'cat_name' => '全棉绒毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '183',
    'cat_name' => '服装盖毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  138 => 
  array (
    'cat_id' => '184',
    'cat_name' => '四季被套毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  139 => 
  array (
    'cat_id' => '190',
    'cat_name' => '羊绒被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '191',
    'cat_name' => '蚕丝被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  141 => 
  array (
    'cat_id' => '192',
    'cat_name' => '羽绒被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  142 => 
  array (
    'cat_id' => '195',
    'cat_name' => '冬被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '2',
    'goods_num' => '9',
  ),
  143 => 
  array (
    'cat_id' => '196',
    'cat_name' => '夏被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  144 => 
  array (
    'cat_id' => '197',
    'cat_name' => '双胎（子母）被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '313',
    'cat_name' => '恒温被',
    'measure_unit' => '',
    'parent_id' => '195',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  146 => 
  array (
    'cat_id' => '314',
    'cat_name' => '丝绵被',
    'measure_unit' => '',
    'parent_id' => '195',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '315',
    'cat_name' => '靠垫被',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  148 => 
  array (
    'cat_id' => '316',
    'cat_name' => '靠垫',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  149 => 
  array (
    'cat_id' => '317',
    'cat_name' => '护颈枕',
    'measure_unit' => '',
    'parent_id' => '205',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  150 => 
  array (
    'cat_id' => '318',
    'cat_name' => '童枕',
    'measure_unit' => '',
    'parent_id' => '205',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  151 => 
  array (
    'cat_id' => '319',
    'cat_name' => '枕芯',
    'measure_unit' => '',
    'parent_id' => '205',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '320',
    'cat_name' => '席枕',
    'measure_unit' => '',
    'parent_id' => '205',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  153 => 
  array (
    'cat_id' => '338',
    'cat_name' => '夏凉席',
    'measure_unit' => '',
    'parent_id' => '206',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  154 => 
  array (
    'cat_id' => '339',
    'cat_name' => '收音机',
    'measure_unit' => '',
    'parent_id' => '219',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  155 => 
  array (
    'cat_id' => '342',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  156 => 
  array (
    'cat_id' => '340',
    'cat_name' => '陶瓷',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '341',
    'cat_name' => '不锈钢',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  158 => 
  array (
    'cat_id' => '390',
    'cat_name' => '时尚真皮',
    'measure_unit' => '',
    'parent_id' => '239',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '236',
    'cat_name' => '手包',
    'measure_unit' => '',
    'parent_id' => '241',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '27',
  ),
  160 => 
  array (
    'cat_id' => '237',
    'cat_name' => '挎包',
    'measure_unit' => '',
    'parent_id' => '241',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  161 => 
  array (
    'cat_id' => '238',
    'cat_name' => '钱包',
    'measure_unit' => '',
    'parent_id' => '241',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 10,
  ),
  162 => 
  array (
    'cat_id' => '240',
    'cat_name' => '卡包',
    'measure_unit' => '',
    'parent_id' => '241',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  163 => 
  array (
    'cat_id' => '387',
    'cat_name' => 'PC拉杆箱',
    'measure_unit' => '',
    'parent_id' => '242',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '388',
    'cat_name' => '真皮商旅包',
    'measure_unit' => '',
    'parent_id' => '242',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '389',
    'cat_name' => '折叠两用包',
    'measure_unit' => '',
    'parent_id' => '242',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '244',
    'cat_name' => '手包',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  167 => 
  array (
    'cat_id' => '245',
    'cat_name' => '栓包',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  168 => 
  array (
    'cat_id' => '246',
    'cat_name' => '钱包',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '247',
    'cat_name' => '卡包',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '207',
    'cat_name' => '电饭煲、电压力锅',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 43,
  ),
  171 => 
  array (
    'cat_id' => '208',
    'cat_name' => '电水壶',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 13,
  ),
  172 => 
  array (
    'cat_id' => '209',
    'cat_name' => '电火锅、电饼档',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 8,
  ),
  173 => 
  array (
    'cat_id' => '215',
    'cat_name' => '微波炉、烤箱、面包机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 9,
  ),
  174 => 
  array (
    'cat_id' => '216',
    'cat_name' => '电陶炉',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 8,
  ),
  175 => 
  array (
    'cat_id' => '217',
    'cat_name' => '电炖锅、煮蛋器',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'goods_num' => 25,
  ),
  176 => 
  array (
    'cat_id' => '128',
    'cat_name' => '养生壶',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => 10,
  ),
  177 => 
  array (
    'cat_id' => '254',
    'cat_name' => '电蒸笼',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  178 => 
  array (
    'cat_id' => '250',
    'cat_name' => '冰激凌机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '297',
    'cat_name' => '电热饭盒',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  180 => 
  array (
    'cat_id' => '234',
    'cat_name' => '豆浆机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 3,
  ),
  181 => 
  array (
    'cat_id' => '251',
    'cat_name' => '酸奶机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 5,
  ),
  182 => 
  array (
    'cat_id' => '326',
    'cat_name' => '咖啡机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  183 => 
  array (
    'cat_id' => '252',
    'cat_name' => '料理机、原汁机、榨汁机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 14,
  ),
  184 => 
  array (
    'cat_id' => '330',
    'cat_name' => '多功能研磨机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  185 => 
  array (
    'cat_id' => '210',
    'cat_name' => '加湿器',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 23,
  ),
  186 => 
  array (
    'cat_id' => '211',
    'cat_name' => '剃须刀',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  187 => 
  array (
    'cat_id' => '212',
    'cat_name' => '挂烫机',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  188 => 
  array (
    'cat_id' => '213',
    'cat_name' => '电吹风',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 14,
  ),
  189 => 
  array (
    'cat_id' => '214',
    'cat_name' => '扫地机、吸尘器',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 14,
  ),
  190 => 
  array (
    'cat_id' => '60',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 16,
  ),
  191 => 
  array (
    'cat_id' => '309',
    'cat_name' => '插座',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
  ),
  192 => 
  array (
    'cat_id' => '285',
    'cat_name' => '干衣机',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  193 => 
  array (
    'cat_id' => '325',
    'cat_name' => '电暖器',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  194 => 
  array (
    'cat_id' => '258',
    'cat_name' => '风扇',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 16,
  ),
  195 => 
  array (
    'cat_id' => '255',
    'cat_name' => '时钟',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
  ),
  196 => 
  array (
    'cat_id' => '286',
    'cat_name' => '果蔬解毒机',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  197 => 
  array (
    'cat_id' => '287',
    'cat_name' => '净化器',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
  ),
  198 => 
  array (
    'cat_id' => '399',
    'cat_name' => '请柬',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  199 => 
  array (
    'cat_id' => '400',
    'cat_name' => '吉祥物',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  200 => 
  array (
    'cat_id' => '401',
    'cat_name' => '纪念章/币',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  201 => 
  array (
    'cat_id' => '402',
    'cat_name' => '定制手机壳',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  202 => 
  array (
    'cat_id' => '396',
    'cat_name' => '花瓶',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  203 => 
  array (
    'cat_id' => '397',
    'cat_name' => '手绘瓷器',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  204 => 
  array (
    'cat_id' => '398',
    'cat_name' => '文房四宝',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  205 => 
  array (
    'cat_id' => '395',
    'cat_name' => '玉器',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  206 => 
  array (
    'cat_id' => '94',
    'cat_name' => '不锈钢 汤锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 32,
  ),
  207 => 
  array (
    'cat_id' => '93',
    'cat_name' => '不锈钢 蒸锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 17,
  ),
  208 => 
  array (
    'cat_id' => '220',
    'cat_name' => '不锈钢 炒锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 14,
  ),
  209 => 
  array (
    'cat_id' => '222',
    'cat_name' => '煎锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 16,
  ),
  210 => 
  array (
    'cat_id' => '91',
    'cat_name' => '奶锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 11,
  ),
  211 => 
  array (
    'cat_id' => '226',
    'cat_name' => '水壶',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  212 => 
  array (
    'cat_id' => '146',
    'cat_name' => '煮面锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  213 => 
  array (
    'cat_id' => '305',
    'cat_name' => '套盆、洗刷篮',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  214 => 
  array (
    'cat_id' => '221',
    'cat_name' => '铸铁炒锅',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  215 => 
  array (
    'cat_id' => '306',
    'cat_name' => '煎锅',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  216 => 
  array (
    'cat_id' => '225',
    'cat_name' => '保温提锅',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 3,
  ),
  217 => 
  array (
    'cat_id' => '156',
    'cat_name' => '居家用品',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => 5,
  ),
  218 => 
  array (
    'cat_id' => '157',
    'cat_name' => '服饰',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => '4',
  ),
  219 => 
  array (
    'cat_id' => '312',
    'cat_name' => '保健食品',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '16',
  ),
  220 => 
  array (
    'cat_id' => '303',
    'cat_name' => '保健器材',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '4',
  ),
  221 => 
  array (
    'cat_id' => '365',
    'cat_name' => '保鲜碗',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  222 => 
  array (
    'cat_id' => '447',
    'cat_name' => '玻璃碗',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  223 => 
  array (
    'cat_id' => '367',
    'cat_name' => '情侣杯',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  224 => 
  array (
    'cat_id' => '360',
    'cat_name' => '碗碟',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  225 => 
  array (
    'cat_id' => '356',
    'cat_name' => '杯壶',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
  ),
  226 => 
  array (
    'cat_id' => '432',
    'cat_name' => '野餐式',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  227 => 
  array (
    'cat_id' => '433',
    'cat_name' => '不锈钢式',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  228 => 
  array (
    'cat_id' => '430',
    'cat_name' => '拉杆箱',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  229 => 
  array (
    'cat_id' => '429',
    'cat_name' => '手提式',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  230 => 
  array (
    'cat_id' => '431',
    'cat_name' => '双肩背式',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  231 => 
  array (
    'cat_id' => '374',
    'cat_name' => '3件套',
    'measure_unit' => '',
    'parent_id' => '281',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  232 => 
  array (
    'cat_id' => '375',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '281',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  233 => 
  array (
    'cat_id' => '372',
    'cat_name' => '礼盒套装',
    'measure_unit' => '',
    'parent_id' => '281',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  234 => 
  array (
    'cat_id' => '373',
    'cat_name' => '2件套',
    'measure_unit' => '',
    'parent_id' => '281',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  235 => 
  array (
    'cat_id' => '377',
    'cat_name' => '幽兰花中式保鲜碗',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  236 => 
  array (
    'cat_id' => '378',
    'cat_name' => '陶瓷保温饭盒',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  237 => 
  array (
    'cat_id' => '376',
    'cat_name' => '优质镁质瓷保鲜盘',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  238 => 
  array (
    'cat_id' => '419',
    'cat_name' => '车载吸尘器',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  239 => 
  array (
    'cat_id' => '418',
    'cat_name' => '两用吸尘器',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  240 => 
  array (
    'cat_id' => '441',
    'cat_name' => '护颈枕头',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  241 => 
  array (
    'cat_id' => '442',
    'cat_name' => '挂件',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  242 => 
  array (
    'cat_id' => '383',
    'cat_name' => '野餐包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  243 => 
  array (
    'cat_id' => '384',
    'cat_name' => '洗漱收纳包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  244 => 
  array (
    'cat_id' => '385',
    'cat_name' => '商务休闲包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  245 => 
  array (
    'cat_id' => '382',
    'cat_name' => '登山包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  246 => 
  array (
    'cat_id' => '386',
    'cat_name' => '电脑双肩包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  247 => 
  array (
    'cat_id' => '79',
    'cat_name' => '保温杯',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  248 => 
  array (
    'cat_id' => '380',
    'cat_name' => '方形饭盒（双层）',
    'measure_unit' => '',
    'parent_id' => '295',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  249 => 
  array (
    'cat_id' => '381',
    'cat_name' => '密扣保鲜盒',
    'measure_unit' => '',
    'parent_id' => '295',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  250 => 
  array (
    'cat_id' => '379',
    'cat_name' => '不锈钢保温瓶饭盒',
    'measure_unit' => '',
    'parent_id' => '295',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  251 => 
  array (
    'cat_id' => '352',
    'cat_name' => '两件套',
    'measure_unit' => '',
    'parent_id' => '296',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  252 => 
  array (
    'cat_id' => '353',
    'cat_name' => '三家套',
    'measure_unit' => '',
    'parent_id' => '296',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  253 => 
  array (
    'cat_id' => '354',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '296',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  254 => 
  array (
    'cat_id' => '351',
    'cat_name' => '一件套',
    'measure_unit' => '',
    'parent_id' => '296',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  255 => 
  array (
    'cat_id' => '438',
    'cat_name' => '行车记录仪',
    'measure_unit' => '',
    'parent_id' => '298',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  256 => 
  array (
    'cat_id' => '439',
    'cat_name' => '夜视功能行车记录仪',
    'measure_unit' => '',
    'parent_id' => '298',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  257 => 
  array (
    'cat_id' => '422',
    'cat_name' => '多功能伸缩整理箱',
    'measure_unit' => '',
    'parent_id' => '299',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  258 => 
  array (
    'cat_id' => '423',
    'cat_name' => '充气泵',
    'measure_unit' => '',
    'parent_id' => '299',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  259 => 
  array (
    'cat_id' => '420',
    'cat_name' => '手机支架',
    'measure_unit' => '',
    'parent_id' => '299',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  260 => 
  array (
    'cat_id' => '421',
    'cat_name' => '车载充电器',
    'measure_unit' => '',
    'parent_id' => '299',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  261 => 
  array (
    'cat_id' => '416',
    'cat_name' => '房子加湿器',
    'measure_unit' => '',
    'parent_id' => '302',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  262 => 
  array (
    'cat_id' => '417',
    'cat_name' => '可爱加湿器',
    'measure_unit' => '',
    'parent_id' => '302',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  263 => 
  array (
    'cat_id' => '337',
    'cat_name' => '颈椎枕',
    'measure_unit' => '',
    'parent_id' => '303',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  264 => 
  array (
    'cat_id' => '335',
    'cat_name' => '血压仪',
    'measure_unit' => '',
    'parent_id' => '303',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  265 => 
  array (
    'cat_id' => '336',
    'cat_name' => '脂肪秤',
    'measure_unit' => '',
    'parent_id' => '303',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  266 => 
  array (
    'cat_id' => '357',
    'cat_name' => '煲锅',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  267 => 
  array (
    'cat_id' => '364',
    'cat_name' => '陶瓷煎锅',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  268 => 
  array (
    'cat_id' => '393',
    'cat_name' => '干货特产',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
  ),
  269 => 
  array (
    'cat_id' => '394',
    'cat_name' => '节日礼盒',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  270 => 
  array (
    'cat_id' => '391',
    'cat_name' => '五谷杂粮大礼包',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  271 => 
  array (
    'cat_id' => '392',
    'cat_name' => '食尚礼盒',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  272 => 
  array (
    'cat_id' => '359',
    'cat_name' => '花瓶',
    'measure_unit' => '',
    'parent_id' => '355',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  273 => 
  array (
    'cat_id' => '428',
    'cat_name' => '帐篷/睡袋',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
  ),
  274 => 
  array (
    'cat_id' => '435',
    'cat_name' => '登山杖',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  275 => 
  array (
    'cat_id' => '425',
    'cat_name' => '烧烤炉',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
  ),
  276 => 
  array (
    'cat_id' => '434',
    'cat_name' => '沙滩椅',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  277 => 
  array (
    'cat_id' => '440',
    'cat_name' => '户外旅行包',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
  ),
  278 => 
  array (
    'cat_id' => '436',
    'cat_name' => '钓鱼凳',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  279 => 
  array (
    'cat_id' => '427',
    'cat_name' => '野餐垫',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  280 => 
  array (
    'cat_id' => '437',
    'cat_name' => '吊床',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  281 => 
  array (
    'cat_id' => '446',
    'cat_name' => '壹礼彩',
    'measure_unit' => '',
    'parent_id' => '445',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  282 => 
  array (
    'cat_id' => '460',
    'cat_name' => '骨瓷杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
  ),
  283 => 
  array (
    'cat_id' => '461',
    'cat_name' => '塑料杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  284 => 
  array (
    'cat_id' => '458',
    'cat_name' => '保温杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '75',
  ),
  285 => 
  array (
    'cat_id' => '462',
    'cat_name' => '陶瓷杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  286 => 
  array (
    'cat_id' => '459',
    'cat_name' => '玻璃杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '69',
  ),
  287 => 
  array (
    'cat_id' => '453',
    'cat_name' => '保温壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  288 => 
  array (
    'cat_id' => '457',
    'cat_name' => '品茶壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  289 => 
  array (
    'cat_id' => '454',
    'cat_name' => '凉水壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  290 => 
  array (
    'cat_id' => '455',
    'cat_name' => '电水壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  291 => 
  array (
    'cat_id' => '452',
    'cat_name' => '旅游壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  292 => 
  array (
    'cat_id' => '456',
    'cat_name' => '咖啡壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  293 => 
  array (
    'cat_id' => '467',
    'cat_name' => '元旦',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  294 => 
  array (
    'cat_id' => '474',
    'cat_name' => '橄榄油',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  295 => 
  array (
    'cat_id' => '464',
    'cat_name' => '端午',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  296 => 
  array (
    'cat_id' => '465',
    'cat_name' => '中秋',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  297 => 
  array (
    'cat_id' => '468',
    'cat_name' => '燕之坊',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  298 => 
  array (
    'cat_id' => '470',
    'cat_name' => '端午粽子',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  299 => 
  array (
    'cat_id' => '472',
    'cat_name' => '端午绿豆糕',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  300 => 
  array (
    'cat_id' => '471',
    'cat_name' => '端午鸭蛋',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  301 => 
  array (
    'cat_id' => '473',
    'cat_name' => '中秋红酒',
    'measure_unit' => '',
    'parent_id' => '465',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  302 => 
  array (
    'cat_id' => '469',
    'cat_name' => '中秋月饼',
    'measure_unit' => '',
    'parent_id' => '465',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>