<?php
$data = array (
  445 => 
  array (
    'cat_id' => '445',
    'cat_name' => '燕之坊',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '1',
    'goods_num' => '1',
    'level' => 0,
    'id' => '445',
    'name' => '燕之坊',
  ),
  446 => 
  array (
    'cat_id' => '446',
    'cat_name' => '壹礼彩',
    'measure_unit' => '',
    'parent_id' => '445',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '446',
    'name' => '壹礼彩',
  ),
  162 => 
  array (
    'cat_id' => '162',
    'cat_name' => '日化',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '2',
    'goods_num' => '11',
    'level' => 0,
    'id' => '162',
    'name' => '日化',
  ),
  334 => 
  array (
    'cat_id' => '334',
    'cat_name' => '个人护理',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '334',
    'name' => '个人护理',
  ),
  449 => 
  array (
    'cat_id' => '449',
    'cat_name' => '毛巾',
    'measure_unit' => '',
    'parent_id' => '162',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '449',
    'name' => '毛巾',
  ),
  153 => 
  array (
    'cat_id' => '153',
    'cat_name' => '杯壶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '0',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '153',
    'name' => '杯壶',
  ),
  292 => 
  array (
    'cat_id' => '292',
    'cat_name' => '杯',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '292',
    'name' => '杯',
  ),
  79 => 
  array (
    'cat_id' => '79',
    'cat_name' => '保温杯',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '79',
    'name' => '保温杯',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => '家纺/家饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 6,
    'level' => 0,
    'id' => '25',
    'name' => '家纺/家饰',
  ),
  163 => 
  array (
    'cat_id' => '163',
    'cat_name' => '四件套',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '5',
    'goods_num' => '8',
    'level' => 1,
    'id' => '163',
    'name' => '四件套',
  ),
  168 => 
  array (
    'cat_id' => '168',
    'cat_name' => '全棉四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 14,
    'level' => 2,
    'id' => '168',
    'name' => '全棉四件套',
  ),
  169 => 
  array (
    'cat_id' => '169',
    'cat_name' => '舒香棉四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '169',
    'name' => '舒香棉四件套',
  ),
  170 => 
  array (
    'cat_id' => '170',
    'cat_name' => '云貂绒四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '170',
    'name' => '云貂绒四件套',
  ),
  322 => 
  array (
    'cat_id' => '322',
    'cat_name' => '雪狐绒四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '322',
    'name' => '雪狐绒四件套',
  ),
  167 => 
  array (
    'cat_id' => '167',
    'cat_name' => '婚庆四件套',
    'measure_unit' => '',
    'parent_id' => '163',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '167',
    'name' => '婚庆四件套',
  ),
  164 => 
  array (
    'cat_id' => '164',
    'cat_name' => '三件套',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 9,
    'level' => 1,
    'id' => '164',
    'name' => '三件套',
  ),
  171 => 
  array (
    'cat_id' => '171',
    'cat_name' => '单人床全棉三件套',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '171',
    'name' => '单人床全棉三件套',
  ),
  172 => 
  array (
    'cat_id' => '172',
    'cat_name' => '双人床全棉三件套（被套+枕套）',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '172',
    'name' => '双人床全棉三件套（被套+枕套）',
  ),
  173 => 
  array (
    'cat_id' => '173',
    'cat_name' => '双人床全棉三件套（床单+枕套）',
    'measure_unit' => '',
    'parent_id' => '164',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 6,
    'level' => 2,
    'id' => '173',
    'name' => '双人床全棉三件套（床单+枕套）',
  ),
  165 => 
  array (
    'cat_id' => '165',
    'cat_name' => '被套',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '165',
    'name' => '被套',
  ),
  301 => 
  array (
    'cat_id' => '301',
    'cat_name' => '高支纯棉被套',
    'measure_unit' => '',
    'parent_id' => '165',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '301',
    'name' => '高支纯棉被套',
  ),
  166 => 
  array (
    'cat_id' => '166',
    'cat_name' => '床单',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '166',
    'name' => '床单',
  ),
  300 => 
  array (
    'cat_id' => '300',
    'cat_name' => '高支纯棉床单',
    'measure_unit' => '',
    'parent_id' => '166',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '300',
    'name' => '高支纯棉床单',
  ),
  180 => 
  array (
    'cat_id' => '180',
    'cat_name' => '被子系列',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => '2',
    'level' => 1,
    'id' => '180',
    'name' => '被子系列',
  ),
  190 => 
  array (
    'cat_id' => '190',
    'cat_name' => '羊绒被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '190',
    'name' => '羊绒被',
  ),
  191 => 
  array (
    'cat_id' => '191',
    'cat_name' => '蚕丝被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '191',
    'name' => '蚕丝被',
  ),
  192 => 
  array (
    'cat_id' => '192',
    'cat_name' => '羽绒被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '192',
    'name' => '羽绒被',
  ),
  195 => 
  array (
    'cat_id' => '195',
    'cat_name' => '冬被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '2',
    'goods_num' => '9',
    'level' => 2,
    'id' => '195',
    'name' => '冬被',
  ),
  313 => 
  array (
    'cat_id' => '313',
    'cat_name' => '恒温被',
    'measure_unit' => '',
    'parent_id' => '195',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 3,
    'id' => '313',
    'name' => '恒温被',
  ),
  314 => 
  array (
    'cat_id' => '314',
    'cat_name' => '丝绵被',
    'measure_unit' => '',
    'parent_id' => '195',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 3,
    'id' => '314',
    'name' => '丝绵被',
  ),
  196 => 
  array (
    'cat_id' => '196',
    'cat_name' => '夏被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '196',
    'name' => '夏被',
  ),
  197 => 
  array (
    'cat_id' => '197',
    'cat_name' => '双胎（子母）被',
    'measure_unit' => '',
    'parent_id' => '180',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '197',
    'name' => '双胎（子母）被',
  ),
  179 => 
  array (
    'cat_id' => '179',
    'cat_name' => '绒毯系列',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '5',
    'goods_num' => '4',
    'level' => 1,
    'id' => '179',
    'name' => '绒毯系列',
  ),
  181 => 
  array (
    'cat_id' => '181',
    'cat_name' => '单层绒毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '181',
    'name' => '单层绒毯',
  ),
  182 => 
  array (
    'cat_id' => '182',
    'cat_name' => '双层绒毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '182',
    'name' => '双层绒毯',
  ),
  186 => 
  array (
    'cat_id' => '186',
    'cat_name' => '全棉绒毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '186',
    'name' => '全棉绒毯',
  ),
  183 => 
  array (
    'cat_id' => '183',
    'cat_name' => '服装盖毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '183',
    'name' => '服装盖毯',
  ),
  184 => 
  array (
    'cat_id' => '184',
    'cat_name' => '四季被套毯',
    'measure_unit' => '',
    'parent_id' => '179',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '184',
    'name' => '四季被套毯',
  ),
  202 => 
  array (
    'cat_id' => '202',
    'cat_name' => '靠垫',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '2',
    'goods_num' => '2',
    'level' => 1,
    'id' => '202',
    'name' => '靠垫',
  ),
  315 => 
  array (
    'cat_id' => '315',
    'cat_name' => '靠垫被',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '315',
    'name' => '靠垫被',
  ),
  316 => 
  array (
    'cat_id' => '316',
    'cat_name' => '靠垫',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '316',
    'name' => '靠垫',
  ),
  205 => 
  array (
    'cat_id' => '205',
    'cat_name' => '枕头、枕芯',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '4',
    'goods_num' => '3',
    'level' => 1,
    'id' => '205',
    'name' => '枕头、枕芯',
  ),
  317 => 
  array (
    'cat_id' => '317',
    'cat_name' => '护颈枕',
    'measure_unit' => '',
    'parent_id' => '205',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '317',
    'name' => '护颈枕',
  ),
  318 => 
  array (
    'cat_id' => '318',
    'cat_name' => '童枕',
    'measure_unit' => '',
    'parent_id' => '205',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '318',
    'name' => '童枕',
  ),
  319 => 
  array (
    'cat_id' => '319',
    'cat_name' => '枕芯',
    'measure_unit' => '',
    'parent_id' => '205',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '319',
    'name' => '枕芯',
  ),
  320 => 
  array (
    'cat_id' => '320',
    'cat_name' => '席枕',
    'measure_unit' => '',
    'parent_id' => '205',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '320',
    'name' => '席枕',
  ),
  206 => 
  array (
    'cat_id' => '206',
    'cat_name' => '席子',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '11',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '206',
    'name' => '席子',
  ),
  338 => 
  array (
    'cat_id' => '338',
    'cat_name' => '夏凉席',
    'measure_unit' => '',
    'parent_id' => '206',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '338',
    'name' => '夏凉席',
  ),
  149 => 
  array (
    'cat_id' => '149',
    'cat_name' => '家电/数码',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '8',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => 143,
    'level' => 0,
    'id' => '149',
    'name' => '家电/数码',
  ),
  263 => 
  array (
    'cat_id' => '263',
    'cat_name' => '厨房电器',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '15',
    'goods_num' => 33,
    'level' => 1,
    'id' => '263',
    'name' => '厨房电器',
  ),
  207 => 
  array (
    'cat_id' => '207',
    'cat_name' => '电饭煲、电压力锅',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 43,
    'level' => 2,
    'id' => '207',
    'name' => '电饭煲、电压力锅',
  ),
  208 => 
  array (
    'cat_id' => '208',
    'cat_name' => '电水壶',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 13,
    'level' => 2,
    'id' => '208',
    'name' => '电水壶',
  ),
  209 => 
  array (
    'cat_id' => '209',
    'cat_name' => '电火锅、电饼档',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 8,
    'level' => 2,
    'id' => '209',
    'name' => '电火锅、电饼档',
  ),
  215 => 
  array (
    'cat_id' => '215',
    'cat_name' => '微波炉、烤箱、面包机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '0',
    'goods_num' => 9,
    'level' => 2,
    'id' => '215',
    'name' => '微波炉、烤箱、面包机',
  ),
  216 => 
  array (
    'cat_id' => '216',
    'cat_name' => '电陶炉',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '0',
    'goods_num' => 8,
    'level' => 2,
    'id' => '216',
    'name' => '电陶炉',
  ),
  217 => 
  array (
    'cat_id' => '217',
    'cat_name' => '电炖锅、煮蛋器',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '13',
    'has_children' => '0',
    'goods_num' => 25,
    'level' => 2,
    'id' => '217',
    'name' => '电炖锅、煮蛋器',
  ),
  128 => 
  array (
    'cat_id' => '128',
    'cat_name' => '养生壶',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '0',
    'goods_num' => 10,
    'level' => 2,
    'id' => '128',
    'name' => '养生壶',
  ),
  254 => 
  array (
    'cat_id' => '254',
    'cat_name' => '电蒸笼',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '254',
    'name' => '电蒸笼',
  ),
  250 => 
  array (
    'cat_id' => '250',
    'cat_name' => '冰激凌机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '250',
    'name' => '冰激凌机',
  ),
  297 => 
  array (
    'cat_id' => '297',
    'cat_name' => '电热饭盒',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '297',
    'name' => '电热饭盒',
  ),
  234 => 
  array (
    'cat_id' => '234',
    'cat_name' => '豆浆机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 2,
    'id' => '234',
    'name' => '豆浆机',
  ),
  251 => 
  array (
    'cat_id' => '251',
    'cat_name' => '酸奶机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 5,
    'level' => 2,
    'id' => '251',
    'name' => '酸奶机',
  ),
  326 => 
  array (
    'cat_id' => '326',
    'cat_name' => '咖啡机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '326',
    'name' => '咖啡机',
  ),
  252 => 
  array (
    'cat_id' => '252',
    'cat_name' => '料理机、原汁机、榨汁机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 14,
    'level' => 2,
    'id' => '252',
    'name' => '料理机、原汁机、榨汁机',
  ),
  330 => 
  array (
    'cat_id' => '330',
    'cat_name' => '多功能研磨机',
    'measure_unit' => '',
    'parent_id' => '263',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '330',
    'name' => '多功能研磨机',
  ),
  264 => 
  array (
    'cat_id' => '264',
    'cat_name' => '生活电器',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '13',
    'goods_num' => 10,
    'level' => 1,
    'id' => '264',
    'name' => '生活电器',
  ),
  210 => 
  array (
    'cat_id' => '210',
    'cat_name' => '加湿器',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '0',
    'goods_num' => 23,
    'level' => 2,
    'id' => '210',
    'name' => '加湿器',
  ),
  211 => 
  array (
    'cat_id' => '211',
    'cat_name' => '剃须刀',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '211',
    'name' => '剃须刀',
  ),
  212 => 
  array (
    'cat_id' => '212',
    'cat_name' => '挂烫机',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 2,
    'id' => '212',
    'name' => '挂烫机',
  ),
  213 => 
  array (
    'cat_id' => '213',
    'cat_name' => '电吹风',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '0',
    'goods_num' => 14,
    'level' => 2,
    'id' => '213',
    'name' => '电吹风',
  ),
  214 => 
  array (
    'cat_id' => '214',
    'cat_name' => '扫地机、吸尘器',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 14,
    'level' => 2,
    'id' => '214',
    'name' => '扫地机、吸尘器',
  ),
  60 => 
  array (
    'cat_id' => '60',
    'cat_name' => '灯具',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => 16,
    'level' => 2,
    'id' => '60',
    'name' => '灯具',
  ),
  309 => 
  array (
    'cat_id' => '309',
    'cat_name' => '插座',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 2,
    'id' => '309',
    'name' => '插座',
  ),
  285 => 
  array (
    'cat_id' => '285',
    'cat_name' => '干衣机',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '285',
    'name' => '干衣机',
  ),
  325 => 
  array (
    'cat_id' => '325',
    'cat_name' => '电暖器',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '325',
    'name' => '电暖器',
  ),
  258 => 
  array (
    'cat_id' => '258',
    'cat_name' => '风扇',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 16,
    'level' => 2,
    'id' => '258',
    'name' => '风扇',
  ),
  255 => 
  array (
    'cat_id' => '255',
    'cat_name' => '时钟',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '255',
    'name' => '时钟',
  ),
  286 => 
  array (
    'cat_id' => '286',
    'cat_name' => '果蔬解毒机',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '286',
    'name' => '果蔬解毒机',
  ),
  287 => 
  array (
    'cat_id' => '287',
    'cat_name' => '净化器',
    'measure_unit' => '',
    'parent_id' => '264',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '11',
    'level' => 2,
    'id' => '287',
    'name' => '净化器',
  ),
  43 => 
  array (
    'cat_id' => '43',
    'cat_name' => '电子产品',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 1,
    'id' => '43',
    'name' => '电子产品',
  ),
  333 => 
  array (
    'cat_id' => '333',
    'cat_name' => '微信产品',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '333',
    'name' => '微信产品',
  ),
  114 => 
  array (
    'cat_id' => '114',
    'cat_name' => '体温计',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '114',
    'name' => '体温计',
  ),
  111 => 
  array (
    'cat_id' => '111',
    'cat_name' => '按摩枕',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '111',
    'name' => '按摩枕',
  ),
  106 => 
  array (
    'cat_id' => '106',
    'cat_name' => '脂肪秤、电子秤',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '47',
    'level' => 2,
    'id' => '106',
    'name' => '脂肪秤、电子秤',
  ),
  112 => 
  array (
    'cat_id' => '112',
    'cat_name' => '治疗仪',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '112',
    'name' => '治疗仪',
  ),
  109 => 
  array (
    'cat_id' => '109',
    'cat_name' => '电动牙刷',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '109',
    'name' => '电动牙刷',
  ),
  126 => 
  array (
    'cat_id' => '126',
    'cat_name' => '足浴器',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '126',
    'name' => '足浴器',
  ),
  113 => 
  array (
    'cat_id' => '113',
    'cat_name' => '计步器',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '113',
    'name' => '计步器',
  ),
  110 => 
  array (
    'cat_id' => '110',
    'cat_name' => '脂肪测量器',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 2,
    'id' => '110',
    'name' => '脂肪测量器',
  ),
  105 => 
  array (
    'cat_id' => '105',
    'cat_name' => '血压计',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 6,
    'level' => 2,
    'id' => '105',
    'name' => '血压计',
  ),
  50 => 
  array (
    'cat_id' => '50',
    'cat_name' => '数码配件',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '6',
    'goods_num' => 19,
    'level' => 1,
    'id' => '50',
    'name' => '数码配件',
  ),
  308 => 
  array (
    'cat_id' => '308',
    'cat_name' => '鼠标',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '308',
    'name' => '鼠标',
  ),
  59 => 
  array (
    'cat_id' => '59',
    'cat_name' => '耳机',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 6,
    'level' => 2,
    'id' => '59',
    'name' => '耳机',
  ),
  95 => 
  array (
    'cat_id' => '95',
    'cat_name' => '鼠标垫',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 6,
    'level' => 2,
    'id' => '95',
    'name' => '鼠标垫',
  ),
  140 => 
  array (
    'cat_id' => '140',
    'cat_name' => 'U盘',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 16,
    'level' => 2,
    'id' => '140',
    'name' => 'U盘',
  ),
  119 => 
  array (
    'cat_id' => '119',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 24,
    'level' => 2,
    'id' => '119',
    'name' => '移动电源',
  ),
  307 => 
  array (
    'cat_id' => '307',
    'cat_name' => '数码套组礼盒',
    'measure_unit' => '',
    'parent_id' => '50',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '307',
    'name' => '数码套组礼盒',
  ),
  52 => 
  array (
    'cat_id' => '52',
    'cat_name' => '时尚影音',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '4',
    'sort_order' => '6',
    'has_children' => '2',
    'goods_num' => 5,
    'level' => 1,
    'id' => '52',
    'name' => '时尚影音',
  ),
  145 => 
  array (
    'cat_id' => '145',
    'cat_name' => 'MP3',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 2,
    'level' => 2,
    'id' => '145',
    'name' => 'MP3',
  ),
  66 => 
  array (
    'cat_id' => '66',
    'cat_name' => '音响',
    'measure_unit' => '',
    'parent_id' => '52',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 10,
    'level' => 2,
    'id' => '66',
    'name' => '音响',
  ),
  219 => 
  array (
    'cat_id' => '219',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '149',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 3,
    'level' => 1,
    'id' => '219',
    'name' => '其他',
  ),
  339 => 
  array (
    'cat_id' => '339',
    'cat_name' => '收音机',
    'measure_unit' => '',
    'parent_id' => '219',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '339',
    'name' => '收音机',
  ),
  151 => 
  array (
    'cat_id' => '151',
    'cat_name' => '厨具/电器',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '3',
    'has_children' => '10',
    'goods_num' => 50,
    'level' => 0,
    'id' => '151',
    'name' => '厨具/电器',
  ),
  271 => 
  array (
    'cat_id' => '271',
    'cat_name' => '不锈钢类',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '271',
    'name' => '不锈钢类',
  ),
  94 => 
  array (
    'cat_id' => '94',
    'cat_name' => '不锈钢 汤锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 32,
    'level' => 2,
    'id' => '94',
    'name' => '不锈钢 汤锅',
  ),
  93 => 
  array (
    'cat_id' => '93',
    'cat_name' => '不锈钢 蒸锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 17,
    'level' => 2,
    'id' => '93',
    'name' => '不锈钢 蒸锅',
  ),
  220 => 
  array (
    'cat_id' => '220',
    'cat_name' => '不锈钢 炒锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 14,
    'level' => 2,
    'id' => '220',
    'name' => '不锈钢 炒锅',
  ),
  222 => 
  array (
    'cat_id' => '222',
    'cat_name' => '煎锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 16,
    'level' => 2,
    'id' => '222',
    'name' => '煎锅',
  ),
  91 => 
  array (
    'cat_id' => '91',
    'cat_name' => '奶锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 11,
    'level' => 2,
    'id' => '91',
    'name' => '奶锅',
  ),
  226 => 
  array (
    'cat_id' => '226',
    'cat_name' => '水壶',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '226',
    'name' => '水壶',
  ),
  146 => 
  array (
    'cat_id' => '146',
    'cat_name' => '煮面锅',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '146',
    'name' => '煮面锅',
  ),
  305 => 
  array (
    'cat_id' => '305',
    'cat_name' => '套盆、洗刷篮',
    'measure_unit' => '',
    'parent_id' => '271',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '305',
    'name' => '套盆、洗刷篮',
  ),
  272 => 
  array (
    'cat_id' => '272',
    'cat_name' => '铸铁类',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '272',
    'name' => '铸铁类',
  ),
  221 => 
  array (
    'cat_id' => '221',
    'cat_name' => '铸铁炒锅',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '221',
    'name' => '铸铁炒锅',
  ),
  306 => 
  array (
    'cat_id' => '306',
    'cat_name' => '煎锅',
    'measure_unit' => '',
    'parent_id' => '272',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '306',
    'name' => '煎锅',
  ),
  273 => 
  array (
    'cat_id' => '273',
    'cat_name' => '提锅类',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '273',
    'name' => '提锅类',
  ),
  225 => 
  array (
    'cat_id' => '225',
    'cat_name' => '保温提锅',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 3,
    'level' => 2,
    'id' => '225',
    'name' => '保温提锅',
  ),
  227 => 
  array (
    'cat_id' => '227',
    'cat_name' => '炊具',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '3',
    'goods_num' => 3,
    'level' => 1,
    'id' => '227',
    'name' => '炊具',
  ),
  342 => 
  array (
    'cat_id' => '342',
    'cat_name' => '套装',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '342',
    'name' => '套装',
  ),
  340 => 
  array (
    'cat_id' => '340',
    'cat_name' => '陶瓷',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '340',
    'name' => '陶瓷',
  ),
  341 => 
  array (
    'cat_id' => '341',
    'cat_name' => '不锈钢',
    'measure_unit' => '',
    'parent_id' => '227',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '341',
    'name' => '不锈钢',
  ),
  88 => 
  array (
    'cat_id' => '88',
    'cat_name' => '锅组套装',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '14',
    'has_children' => '4',
    'goods_num' => 83,
    'level' => 1,
    'id' => '88',
    'name' => '锅组套装',
  ),
  346 => 
  array (
    'cat_id' => '346',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '346',
    'name' => '其他',
  ),
  343 => 
  array (
    'cat_id' => '343',
    'cat_name' => '两件套',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '343',
    'name' => '两件套',
  ),
  344 => 
  array (
    'cat_id' => '344',
    'cat_name' => '三件套',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '344',
    'name' => '三件套',
  ),
  345 => 
  array (
    'cat_id' => '345',
    'cat_name' => '四件套',
    'measure_unit' => '',
    'parent_id' => '88',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '345',
    'name' => '四件套',
  ),
  147 => 
  array (
    'cat_id' => '147',
    'cat_name' => '储物容器',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 19,
    'level' => 1,
    'id' => '147',
    'name' => '储物容器',
  ),
  347 => 
  array (
    'cat_id' => '347',
    'cat_name' => '果盘',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '347',
    'name' => '果盘',
  ),
  348 => 
  array (
    'cat_id' => '348',
    'cat_name' => '调味瓶',
    'measure_unit' => '',
    'parent_id' => '147',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '348',
    'name' => '调味瓶',
  ),
  87 => 
  array (
    'cat_id' => '87',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 12,
    'level' => 1,
    'id' => '87',
    'name' => '餐具',
  ),
  256 => 
  array (
    'cat_id' => '256',
    'cat_name' => '竹筷',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '256',
    'name' => '竹筷',
  ),
  361 => 
  array (
    'cat_id' => '361',
    'cat_name' => '不锈钢',
    'measure_unit' => '',
    'parent_id' => '87',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '361',
    'name' => '不锈钢',
  ),
  448 => 
  array (
    'cat_id' => '448',
    'cat_name' => '砧板',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '448',
    'name' => '砧板',
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '刀具',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 20,
    'level' => 1,
    'id' => '99',
    'name' => '刀具',
  ),
  349 => 
  array (
    'cat_id' => '349',
    'cat_name' => '陶瓷刀',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '39',
    'level' => 2,
    'id' => '349',
    'name' => '陶瓷刀',
  ),
  350 => 
  array (
    'cat_id' => '350',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '99',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '350',
    'name' => '其他',
  ),
  296 => 
  array (
    'cat_id' => '296',
    'cat_name' => '调味瓶',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '26',
    'level' => 1,
    'id' => '296',
    'name' => '调味瓶',
  ),
  352 => 
  array (
    'cat_id' => '352',
    'cat_name' => '两件套',
    'measure_unit' => '',
    'parent_id' => '296',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '352',
    'name' => '两件套',
  ),
  353 => 
  array (
    'cat_id' => '353',
    'cat_name' => '三家套',
    'measure_unit' => '',
    'parent_id' => '296',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '353',
    'name' => '三家套',
  ),
  354 => 
  array (
    'cat_id' => '354',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '296',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '354',
    'name' => '其他',
  ),
  351 => 
  array (
    'cat_id' => '351',
    'cat_name' => '一件套',
    'measure_unit' => '',
    'parent_id' => '296',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '351',
    'name' => '一件套',
  ),
  152 => 
  array (
    'cat_id' => '152',
    'cat_name' => '瓷器/杯壶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '6',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 19,
    'level' => 0,
    'id' => '152',
    'name' => '瓷器/杯壶',
  ),
  355 => 
  array (
    'cat_id' => '355',
    'cat_name' => '装饰品',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 1,
    'id' => '355',
    'name' => '装饰品',
  ),
  359 => 
  array (
    'cat_id' => '359',
    'cat_name' => '花瓶',
    'measure_unit' => '',
    'parent_id' => '355',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '359',
    'name' => '花瓶',
  ),
  450 => 
  array (
    'cat_id' => '450',
    'cat_name' => '杯具',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 1,
    'id' => '450',
    'name' => '杯具',
  ),
  460 => 
  array (
    'cat_id' => '460',
    'cat_name' => '骨瓷杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '25',
    'level' => 2,
    'id' => '460',
    'name' => '骨瓷杯',
  ),
  461 => 
  array (
    'cat_id' => '461',
    'cat_name' => '塑料杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '461',
    'name' => '塑料杯',
  ),
  458 => 
  array (
    'cat_id' => '458',
    'cat_name' => '保温杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '75',
    'level' => 2,
    'id' => '458',
    'name' => '保温杯',
  ),
  462 => 
  array (
    'cat_id' => '462',
    'cat_name' => '陶瓷杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '462',
    'name' => '陶瓷杯',
  ),
  459 => 
  array (
    'cat_id' => '459',
    'cat_name' => '玻璃杯',
    'measure_unit' => '',
    'parent_id' => '450',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '69',
    'level' => 2,
    'id' => '459',
    'name' => '玻璃杯',
  ),
  451 => 
  array (
    'cat_id' => '451',
    'cat_name' => '壶类',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => '9',
    'level' => 1,
    'id' => '451',
    'name' => '壶类',
  ),
  453 => 
  array (
    'cat_id' => '453',
    'cat_name' => '保温壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '453',
    'name' => '保温壶',
  ),
  457 => 
  array (
    'cat_id' => '457',
    'cat_name' => '品茶壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '457',
    'name' => '品茶壶',
  ),
  454 => 
  array (
    'cat_id' => '454',
    'cat_name' => '凉水壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '454',
    'name' => '凉水壶',
  ),
  455 => 
  array (
    'cat_id' => '455',
    'cat_name' => '电水壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '455',
    'name' => '电水壶',
  ),
  452 => 
  array (
    'cat_id' => '452',
    'cat_name' => '旅游壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '452',
    'name' => '旅游壶',
  ),
  456 => 
  array (
    'cat_id' => '456',
    'cat_name' => '咖啡壶',
    'measure_unit' => '',
    'parent_id' => '451',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '456',
    'name' => '咖啡壶',
  ),
  311 => 
  array (
    'cat_id' => '311',
    'cat_name' => '炊具',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 5,
    'level' => 1,
    'id' => '311',
    'name' => '炊具',
  ),
  357 => 
  array (
    'cat_id' => '357',
    'cat_name' => '煲锅',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '357',
    'name' => '煲锅',
  ),
  364 => 
  array (
    'cat_id' => '364',
    'cat_name' => '陶瓷煎锅',
    'measure_unit' => '',
    'parent_id' => '311',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '364',
    'name' => '陶瓷煎锅',
  ),
  276 => 
  array (
    'cat_id' => '276',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '152',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 30,
    'level' => 1,
    'id' => '276',
    'name' => '餐具',
  ),
  365 => 
  array (
    'cat_id' => '365',
    'cat_name' => '保鲜碗',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '365',
    'name' => '保鲜碗',
  ),
  447 => 
  array (
    'cat_id' => '447',
    'cat_name' => '玻璃碗',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '447',
    'name' => '玻璃碗',
  ),
  367 => 
  array (
    'cat_id' => '367',
    'cat_name' => '情侣杯',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '367',
    'name' => '情侣杯',
  ),
  360 => 
  array (
    'cat_id' => '360',
    'cat_name' => '碗碟',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '360',
    'name' => '碗碟',
  ),
  356 => 
  array (
    'cat_id' => '356',
    'cat_name' => '杯壶',
    'measure_unit' => '',
    'parent_id' => '276',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '20',
    'level' => 2,
    'id' => '356',
    'name' => '杯壶',
  ),
  154 => 
  array (
    'cat_id' => '154',
    'cat_name' => '保鲜/饭盒',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '3',
    'goods_num' => '4',
    'level' => 0,
    'id' => '154',
    'name' => '保鲜/饭盒',
  ),
  281 => 
  array (
    'cat_id' => '281',
    'cat_name' => '玻璃保鲜盒系列',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => '59',
    'level' => 1,
    'id' => '281',
    'name' => '玻璃保鲜盒系列',
  ),
  374 => 
  array (
    'cat_id' => '374',
    'cat_name' => '3件套',
    'measure_unit' => '',
    'parent_id' => '281',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '374',
    'name' => '3件套',
  ),
  375 => 
  array (
    'cat_id' => '375',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '281',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '375',
    'name' => '其他',
  ),
  372 => 
  array (
    'cat_id' => '372',
    'cat_name' => '礼盒套装',
    'measure_unit' => '',
    'parent_id' => '281',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '372',
    'name' => '礼盒套装',
  ),
  373 => 
  array (
    'cat_id' => '373',
    'cat_name' => '2件套',
    'measure_unit' => '',
    'parent_id' => '281',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '373',
    'name' => '2件套',
  ),
  283 => 
  array (
    'cat_id' => '283',
    'cat_name' => '瓷器保鲜盒系列',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => '3',
    'level' => 1,
    'id' => '283',
    'name' => '瓷器保鲜盒系列',
  ),
  377 => 
  array (
    'cat_id' => '377',
    'cat_name' => '幽兰花中式保鲜碗',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '377',
    'name' => '幽兰花中式保鲜碗',
  ),
  378 => 
  array (
    'cat_id' => '378',
    'cat_name' => '陶瓷保温饭盒',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '378',
    'name' => '陶瓷保温饭盒',
  ),
  376 => 
  array (
    'cat_id' => '376',
    'cat_name' => '优质镁质瓷保鲜盘',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '376',
    'name' => '优质镁质瓷保鲜盘',
  ),
  295 => 
  array (
    'cat_id' => '295',
    'cat_name' => '不锈钢保鲜盒系列',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 13,
    'level' => 1,
    'id' => '295',
    'name' => '不锈钢保鲜盒系列',
  ),
  380 => 
  array (
    'cat_id' => '380',
    'cat_name' => '方形饭盒（双层）',
    'measure_unit' => '',
    'parent_id' => '295',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '380',
    'name' => '方形饭盒（双层）',
  ),
  381 => 
  array (
    'cat_id' => '381',
    'cat_name' => '密扣保鲜盒',
    'measure_unit' => '',
    'parent_id' => '295',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '381',
    'name' => '密扣保鲜盒',
  ),
  379 => 
  array (
    'cat_id' => '379',
    'cat_name' => '不锈钢保温瓶饭盒',
    'measure_unit' => '',
    'parent_id' => '295',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '379',
    'name' => '不锈钢保温瓶饭盒',
  ),
  155 => 
  array (
    'cat_id' => '155',
    'cat_name' => '皮具/箱包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '5',
    'goods_num' => 12,
    'level' => 0,
    'id' => '155',
    'name' => '皮具/箱包',
  ),
  239 => 
  array (
    'cat_id' => '239',
    'cat_name' => '锁匙包',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '1',
    'goods_num' => '15',
    'level' => 1,
    'id' => '239',
    'name' => '锁匙包',
  ),
  390 => 
  array (
    'cat_id' => '390',
    'cat_name' => '时尚真皮',
    'measure_unit' => '',
    'parent_id' => '239',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '390',
    'name' => '时尚真皮',
  ),
  242 => 
  array (
    'cat_id' => '242',
    'cat_name' => '旅行箱包',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => '26',
    'level' => 1,
    'id' => '242',
    'name' => '旅行箱包',
  ),
  387 => 
  array (
    'cat_id' => '387',
    'cat_name' => 'PC拉杆箱',
    'measure_unit' => '',
    'parent_id' => '242',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '387',
    'name' => 'PC拉杆箱',
  ),
  388 => 
  array (
    'cat_id' => '388',
    'cat_name' => '真皮商旅包',
    'measure_unit' => '',
    'parent_id' => '242',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '388',
    'name' => '真皮商旅包',
  ),
  389 => 
  array (
    'cat_id' => '389',
    'cat_name' => '折叠两用包',
    'measure_unit' => '',
    'parent_id' => '242',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '389',
    'name' => '折叠两用包',
  ),
  291 => 
  array (
    'cat_id' => '291',
    'cat_name' => '休闲背包',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '5',
    'goods_num' => 18,
    'level' => 1,
    'id' => '291',
    'name' => '休闲背包',
  ),
  383 => 
  array (
    'cat_id' => '383',
    'cat_name' => '野餐包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '383',
    'name' => '野餐包',
  ),
  384 => 
  array (
    'cat_id' => '384',
    'cat_name' => '洗漱收纳包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '384',
    'name' => '洗漱收纳包',
  ),
  385 => 
  array (
    'cat_id' => '385',
    'cat_name' => '商务休闲包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '385',
    'name' => '商务休闲包',
  ),
  382 => 
  array (
    'cat_id' => '382',
    'cat_name' => '登山包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '382',
    'name' => '登山包',
  ),
  386 => 
  array (
    'cat_id' => '386',
    'cat_name' => '电脑双肩包',
    'measure_unit' => '',
    'parent_id' => '291',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '386',
    'name' => '电脑双肩包',
  ),
  241 => 
  array (
    'cat_id' => '241',
    'cat_name' => '男款',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '4',
    'goods_num' => '38',
    'level' => 1,
    'id' => '241',
    'name' => '男款',
  ),
  236 => 
  array (
    'cat_id' => '236',
    'cat_name' => '手包',
    'measure_unit' => '',
    'parent_id' => '241',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '27',
    'level' => 2,
    'id' => '236',
    'name' => '手包',
  ),
  237 => 
  array (
    'cat_id' => '237',
    'cat_name' => '挎包',
    'measure_unit' => '',
    'parent_id' => '241',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 2,
    'id' => '237',
    'name' => '挎包',
  ),
  238 => 
  array (
    'cat_id' => '238',
    'cat_name' => '钱包',
    'measure_unit' => '',
    'parent_id' => '241',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 10,
    'level' => 2,
    'id' => '238',
    'name' => '钱包',
  ),
  240 => 
  array (
    'cat_id' => '240',
    'cat_name' => '卡包',
    'measure_unit' => '',
    'parent_id' => '241',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 2,
    'id' => '240',
    'name' => '卡包',
  ),
  243 => 
  array (
    'cat_id' => '243',
    'cat_name' => '女款',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 1,
    'id' => '243',
    'name' => '女款',
  ),
  244 => 
  array (
    'cat_id' => '244',
    'cat_name' => '手包',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '244',
    'name' => '手包',
  ),
  245 => 
  array (
    'cat_id' => '245',
    'cat_name' => '栓包',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '245',
    'name' => '栓包',
  ),
  246 => 
  array (
    'cat_id' => '246',
    'cat_name' => '钱包',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '246',
    'name' => '钱包',
  ),
  247 => 
  array (
    'cat_id' => '247',
    'cat_name' => '卡包',
    'measure_unit' => '',
    'parent_id' => '243',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '247',
    'name' => '卡包',
  ),
  274 => 
  array (
    'cat_id' => '274',
    'cat_name' => '居家/服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '2',
    'goods_num' => '9',
    'level' => 0,
    'id' => '274',
    'name' => '居家/服饰',
  ),
  156 => 
  array (
    'cat_id' => '156',
    'cat_name' => '居家用品',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '7',
    'goods_num' => 5,
    'level' => 1,
    'id' => '156',
    'name' => '居家用品',
  ),
  265 => 
  array (
    'cat_id' => '265',
    'cat_name' => '毛巾',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '43',
    'level' => 2,
    'id' => '265',
    'name' => '毛巾',
  ),
  266 => 
  array (
    'cat_id' => '266',
    'cat_name' => '储物纳箱',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 2,
    'id' => '266',
    'name' => '储物纳箱',
  ),
  267 => 
  array (
    'cat_id' => '267',
    'cat_name' => '拖把',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '267',
    'name' => '拖把',
  ),
  270 => 
  array (
    'cat_id' => '270',
    'cat_name' => '晾衣架',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '270',
    'name' => '晾衣架',
  ),
  321 => 
  array (
    'cat_id' => '321',
    'cat_name' => '雨具',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 2,
    'id' => '321',
    'name' => '雨具',
  ),
  310 => 
  array (
    'cat_id' => '310',
    'cat_name' => '指甲包套装',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '35',
    'level' => 2,
    'id' => '310',
    'name' => '指甲包套装',
  ),
  284 => 
  array (
    'cat_id' => '284',
    'cat_name' => '梳子',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 2,
    'id' => '284',
    'name' => '梳子',
  ),
  157 => 
  array (
    'cat_id' => '157',
    'cat_name' => '服饰',
    'measure_unit' => '',
    'parent_id' => '274',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '6',
    'goods_num' => '4',
    'level' => 1,
    'id' => '157',
    'name' => '服饰',
  ),
  198 => 
  array (
    'cat_id' => '198',
    'cat_name' => '睡衣',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '198',
    'name' => '睡衣',
  ),
  199 => 
  array (
    'cat_id' => '199',
    'cat_name' => '拖鞋',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '199',
    'name' => '拖鞋',
  ),
  200 => 
  array (
    'cat_id' => '200',
    'cat_name' => '衬衫',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '200',
    'name' => '衬衫',
  ),
  201 => 
  array (
    'cat_id' => '201',
    'cat_name' => '丝巾、围巾',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '0',
    'goods_num' => 8,
    'level' => 2,
    'id' => '201',
    'name' => '丝巾、围巾',
  ),
  249 => 
  array (
    'cat_id' => '249',
    'cat_name' => '领带',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '249',
    'name' => '领带',
  ),
  324 => 
  array (
    'cat_id' => '324',
    'cat_name' => '手套',
    'measure_unit' => '',
    'parent_id' => '157',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '324',
    'name' => '手套',
  ),
  463 => 
  array (
    'cat_id' => '463',
    'cat_name' => '食品/粗粮',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '8',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '463',
    'name' => '食品/粗粮',
  ),
  467 => 
  array (
    'cat_id' => '467',
    'cat_name' => '元旦',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '467',
    'name' => '元旦',
  ),
  474 => 
  array (
    'cat_id' => '474',
    'cat_name' => '橄榄油',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '474',
    'name' => '橄榄油',
  ),
  464 => 
  array (
    'cat_id' => '464',
    'cat_name' => '端午',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 1,
    'id' => '464',
    'name' => '端午',
  ),
  470 => 
  array (
    'cat_id' => '470',
    'cat_name' => '端午粽子',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '470',
    'name' => '端午粽子',
  ),
  472 => 
  array (
    'cat_id' => '472',
    'cat_name' => '端午绿豆糕',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '472',
    'name' => '端午绿豆糕',
  ),
  471 => 
  array (
    'cat_id' => '471',
    'cat_name' => '端午鸭蛋',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '471',
    'name' => '端午鸭蛋',
  ),
  465 => 
  array (
    'cat_id' => '465',
    'cat_name' => '中秋',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
    'level' => 1,
    'id' => '465',
    'name' => '中秋',
  ),
  473 => 
  array (
    'cat_id' => '473',
    'cat_name' => '中秋红酒',
    'measure_unit' => '',
    'parent_id' => '465',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '473',
    'name' => '中秋红酒',
  ),
  469 => 
  array (
    'cat_id' => '469',
    'cat_name' => '中秋月饼',
    'measure_unit' => '',
    'parent_id' => '465',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '469',
    'name' => '中秋月饼',
  ),
  468 => 
  array (
    'cat_id' => '468',
    'cat_name' => '燕之坊',
    'measure_unit' => '',
    'parent_id' => '463',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '468',
    'name' => '燕之坊',
  ),
  275 => 
  array (
    'cat_id' => '275',
    'cat_name' => '生活/保健',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '9',
    'has_children' => '2',
    'goods_num' => 21,
    'level' => 0,
    'id' => '275',
    'name' => '生活/保健',
  ),
  312 => 
  array (
    'cat_id' => '312',
    'cat_name' => '保健食品',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '16',
    'level' => 1,
    'id' => '312',
    'name' => '保健食品',
  ),
  393 => 
  array (
    'cat_id' => '393',
    'cat_name' => '干货特产',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 2,
    'id' => '393',
    'name' => '干货特产',
  ),
  394 => 
  array (
    'cat_id' => '394',
    'cat_name' => '节日礼盒',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '394',
    'name' => '节日礼盒',
  ),
  391 => 
  array (
    'cat_id' => '391',
    'cat_name' => '五谷杂粮大礼包',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '391',
    'name' => '五谷杂粮大礼包',
  ),
  392 => 
  array (
    'cat_id' => '392',
    'cat_name' => '食尚礼盒',
    'measure_unit' => '',
    'parent_id' => '312',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '392',
    'name' => '食尚礼盒',
  ),
  303 => 
  array (
    'cat_id' => '303',
    'cat_name' => '保健器材',
    'measure_unit' => '',
    'parent_id' => '275',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => '4',
    'level' => 1,
    'id' => '303',
    'name' => '保健器材',
  ),
  337 => 
  array (
    'cat_id' => '337',
    'cat_name' => '颈椎枕',
    'measure_unit' => '',
    'parent_id' => '303',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '337',
    'name' => '颈椎枕',
  ),
  335 => 
  array (
    'cat_id' => '335',
    'cat_name' => '血压仪',
    'measure_unit' => '',
    'parent_id' => '303',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '335',
    'name' => '血压仪',
  ),
  336 => 
  array (
    'cat_id' => '336',
    'cat_name' => '脂肪秤',
    'measure_unit' => '',
    'parent_id' => '303',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '336',
    'name' => '脂肪秤',
  ),
  159 => 
  array (
    'cat_id' => '159',
    'cat_name' => '工艺/日化',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '2',
    'goods_num' => '1',
    'level' => 0,
    'id' => '159',
    'name' => '工艺/日化',
  ),
  269 => 
  array (
    'cat_id' => '269',
    'cat_name' => '开业摆件',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => '6',
    'level' => 1,
    'id' => '269',
    'name' => '开业摆件',
  ),
  396 => 
  array (
    'cat_id' => '396',
    'cat_name' => '花瓶',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '396',
    'name' => '花瓶',
  ),
  397 => 
  array (
    'cat_id' => '397',
    'cat_name' => '手绘瓷器',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '397',
    'name' => '手绘瓷器',
  ),
  398 => 
  array (
    'cat_id' => '398',
    'cat_name' => '文房四宝',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '398',
    'name' => '文房四宝',
  ),
  395 => 
  array (
    'cat_id' => '395',
    'cat_name' => '玉器',
    'measure_unit' => '',
    'parent_id' => '269',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '395',
    'name' => '玉器',
  ),
  268 => 
  array (
    'cat_id' => '268',
    'cat_name' => '精美饰品',
    'measure_unit' => '',
    'parent_id' => '159',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => '73',
    'level' => 1,
    'id' => '268',
    'name' => '精美饰品',
  ),
  399 => 
  array (
    'cat_id' => '399',
    'cat_name' => '请柬',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '399',
    'name' => '请柬',
  ),
  400 => 
  array (
    'cat_id' => '400',
    'cat_name' => '吉祥物',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '400',
    'name' => '吉祥物',
  ),
  401 => 
  array (
    'cat_id' => '401',
    'cat_name' => '纪念章/币',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '401',
    'name' => '纪念章/币',
  ),
  402 => 
  array (
    'cat_id' => '402',
    'cat_name' => '定制手机壳',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '402',
    'name' => '定制手机壳',
  ),
  161 => 
  array (
    'cat_id' => '161',
    'cat_name' => '汽车/配件/户外',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '8',
    'goods_num' => 5,
    'level' => 0,
    'id' => '161',
    'name' => '汽车/配件/户外',
  ),
  288 => 
  array (
    'cat_id' => '288',
    'cat_name' => '车载吸尘器',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => '2',
    'level' => 1,
    'id' => '288',
    'name' => '车载吸尘器',
  ),
  419 => 
  array (
    'cat_id' => '419',
    'cat_name' => '车载吸尘器',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '419',
    'name' => '车载吸尘器',
  ),
  418 => 
  array (
    'cat_id' => '418',
    'cat_name' => '两用吸尘器',
    'measure_unit' => '',
    'parent_id' => '288',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '418',
    'name' => '两用吸尘器',
  ),
  302 => 
  array (
    'cat_id' => '302',
    'cat_name' => '车载加湿器',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '2',
    'goods_num' => '3',
    'level' => 1,
    'id' => '302',
    'name' => '车载加湿器',
  ),
  416 => 
  array (
    'cat_id' => '416',
    'cat_name' => '房子加湿器',
    'measure_unit' => '',
    'parent_id' => '302',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '416',
    'name' => '房子加湿器',
  ),
  417 => 
  array (
    'cat_id' => '417',
    'cat_name' => '可爱加湿器',
    'measure_unit' => '',
    'parent_id' => '302',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '417',
    'name' => '可爱加湿器',
  ),
  277 => 
  array (
    'cat_id' => '277',
    'cat_name' => '冷热箱',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => '10',
    'level' => 1,
    'id' => '277',
    'name' => '冷热箱',
  ),
  432 => 
  array (
    'cat_id' => '432',
    'cat_name' => '野餐式',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '432',
    'name' => '野餐式',
  ),
  433 => 
  array (
    'cat_id' => '433',
    'cat_name' => '不锈钢式',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '433',
    'name' => '不锈钢式',
  ),
  430 => 
  array (
    'cat_id' => '430',
    'cat_name' => '拉杆箱',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '430',
    'name' => '拉杆箱',
  ),
  429 => 
  array (
    'cat_id' => '429',
    'cat_name' => '手提式',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '429',
    'name' => '手提式',
  ),
  431 => 
  array (
    'cat_id' => '431',
    'cat_name' => '双肩背式',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '431',
    'name' => '双肩背式',
  ),
  298 => 
  array (
    'cat_id' => '298',
    'cat_name' => '记录仪',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => '9',
    'level' => 1,
    'id' => '298',
    'name' => '记录仪',
  ),
  438 => 
  array (
    'cat_id' => '438',
    'cat_name' => '行车记录仪',
    'measure_unit' => '',
    'parent_id' => '298',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '438',
    'name' => '行车记录仪',
  ),
  439 => 
  array (
    'cat_id' => '439',
    'cat_name' => '夜视功能行车记录仪',
    'measure_unit' => '',
    'parent_id' => '298',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '439',
    'name' => '夜视功能行车记录仪',
  ),
  290 => 
  array (
    'cat_id' => '290',
    'cat_name' => '车饰',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 2,
    'level' => 1,
    'id' => '290',
    'name' => '车饰',
  ),
  441 => 
  array (
    'cat_id' => '441',
    'cat_name' => '护颈枕头',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '441',
    'name' => '护颈枕头',
  ),
  442 => 
  array (
    'cat_id' => '442',
    'cat_name' => '挂件',
    'measure_unit' => '',
    'parent_id' => '290',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '442',
    'name' => '挂件',
  ),
  424 => 
  array (
    'cat_id' => '424',
    'cat_name' => '户外用品',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 1,
    'id' => '424',
    'name' => '户外用品',
  ),
  428 => 
  array (
    'cat_id' => '428',
    'cat_name' => '帐篷/睡袋',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 2,
    'id' => '428',
    'name' => '帐篷/睡袋',
  ),
  435 => 
  array (
    'cat_id' => '435',
    'cat_name' => '登山杖',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '435',
    'name' => '登山杖',
  ),
  425 => 
  array (
    'cat_id' => '425',
    'cat_name' => '烧烤炉',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 2,
    'id' => '425',
    'name' => '烧烤炉',
  ),
  434 => 
  array (
    'cat_id' => '434',
    'cat_name' => '沙滩椅',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 2,
    'id' => '434',
    'name' => '沙滩椅',
  ),
  440 => 
  array (
    'cat_id' => '440',
    'cat_name' => '户外旅行包',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 2,
    'id' => '440',
    'name' => '户外旅行包',
  ),
  436 => 
  array (
    'cat_id' => '436',
    'cat_name' => '钓鱼凳',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '436',
    'name' => '钓鱼凳',
  ),
  427 => 
  array (
    'cat_id' => '427',
    'cat_name' => '野餐垫',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 2,
    'id' => '427',
    'name' => '野餐垫',
  ),
  437 => 
  array (
    'cat_id' => '437',
    'cat_name' => '吊床',
    'measure_unit' => '',
    'parent_id' => '424',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 2,
    'id' => '437',
    'name' => '吊床',
  ),
  299 => 
  array (
    'cat_id' => '299',
    'cat_name' => '车载工具',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => '13',
    'level' => 1,
    'id' => '299',
    'name' => '车载工具',
  ),
  422 => 
  array (
    'cat_id' => '422',
    'cat_name' => '多功能伸缩整理箱',
    'measure_unit' => '',
    'parent_id' => '299',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '422',
    'name' => '多功能伸缩整理箱',
  ),
  423 => 
  array (
    'cat_id' => '423',
    'cat_name' => '充气泵',
    'measure_unit' => '',
    'parent_id' => '299',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '423',
    'name' => '充气泵',
  ),
  420 => 
  array (
    'cat_id' => '420',
    'cat_name' => '手机支架',
    'measure_unit' => '',
    'parent_id' => '299',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '420',
    'name' => '手机支架',
  ),
  421 => 
  array (
    'cat_id' => '421',
    'cat_name' => '车载充电器',
    'measure_unit' => '',
    'parent_id' => '299',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '421',
    'name' => '车载充电器',
  ),
  257 => 
  array (
    'cat_id' => '257',
    'cat_name' => '车载净化器',
    'measure_unit' => '',
    'parent_id' => '161',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 6,
    'level' => 1,
    'id' => '257',
    'name' => '车载净化器',
  ),
  160 => 
  array (
    'cat_id' => '160',
    'cat_name' => '商务/办公/用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '12',
    'has_children' => '2',
    'goods_num' => 4,
    'level' => 0,
    'id' => '160',
    'name' => '商务/办公/用品',
  ),
  53 => 
  array (
    'cat_id' => '53',
    'cat_name' => '商务广告',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '3',
    'goods_num' => 10,
    'level' => 1,
    'id' => '53',
    'name' => '商务广告',
  ),
  403 => 
  array (
    'cat_id' => '403',
    'cat_name' => '定做广告伞',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '403',
    'name' => '定做广告伞',
  ),
  404 => 
  array (
    'cat_id' => '404',
    'cat_name' => '定做购物袋',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '404',
    'name' => '定做购物袋',
  ),
  405 => 
  array (
    'cat_id' => '405',
    'cat_name' => '定做广告衫',
    'measure_unit' => '',
    'parent_id' => '53',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '405',
    'name' => '定做广告衫',
  ),
  158 => 
  array (
    'cat_id' => '158',
    'cat_name' => '办公用品',
    'measure_unit' => '',
    'parent_id' => '160',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '11',
    'has_children' => '11',
    'goods_num' => 65,
    'level' => 1,
    'id' => '158',
    'name' => '办公用品',
  ),
  415 => 
  array (
    'cat_id' => '415',
    'cat_name' => '鼠标垫',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '415',
    'name' => '鼠标垫',
  ),
  412 => 
  array (
    'cat_id' => '412',
    'cat_name' => '计算器',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '412',
    'name' => '计算器',
  ),
  409 => 
  array (
    'cat_id' => '409',
    'cat_name' => '公文夹',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '409',
    'name' => '公文夹',
  ),
  406 => 
  array (
    'cat_id' => '406',
    'cat_name' => '活页本',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '406',
    'name' => '活页本',
  ),
  413 => 
  array (
    'cat_id' => '413',
    'cat_name' => 'U盘',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '413',
    'name' => 'U盘',
  ),
  443 => 
  array (
    'cat_id' => '443',
    'cat_name' => '邀请函',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 2,
    'id' => '443',
    'name' => '邀请函',
  ),
  410 => 
  array (
    'cat_id' => '410',
    'cat_name' => '商务签字笔',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '410',
    'name' => '商务签字笔',
  ),
  407 => 
  array (
    'cat_id' => '407',
    'cat_name' => '笔记本',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '407',
    'name' => '笔记本',
  ),
  414 => 
  array (
    'cat_id' => '414',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '414',
    'name' => '移动电源',
  ),
  411 => 
  array (
    'cat_id' => '411',
    'cat_name' => '名片盒',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '411',
    'name' => '名片盒',
  ),
  408 => 
  array (
    'cat_id' => '408',
    'cat_name' => '拉链包',
    'measure_unit' => '',
    'parent_id' => '158',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 2,
    'id' => '408',
    'name' => '拉链包',
  ),
  475 => 
  array (
    'cat_id' => '475',
    'cat_name' => '花草茶',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '475',
    'name' => '花草茶',
  ),
);
?>